spring.application.name=spring_oracle_tutorial

# spring.datasource.url=jdbc:oracle:thin:@localhost:1522/FREEPDB1
# spring.datasource.username=system
# spring.datasource.password=admin123
# spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# spring.datasource.url=jdbc:oracle:thin:@localhost:1522/FREEPDB1
# spring.datasource.username=system
# spring.datasource.password=${ORACLE_DB_PASSWORD:admin123}
# spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# # Oracle automatic backup
# oracle.backup.enabled=true
# oracle.backup.schema=SYSTEM
# oracle.backup.cron=0 * * * * *
# oracle.backup.directory=DATA_PUMP_DIR
# oracle.backup.local-folder=./backups


# Oracle database connection
spring.datasource.url=jdbc:oracle:thin:@localhost:1522/FREEPDB1
spring.datasource.username=system
spring.datasource.password=admin123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Oracle backup settings
oracle.backup.enabled=true
oracle.backup.username=system
oracle.backup.password=admin123
oracle.backup.connect=//localhost:1522/FREEPDB1
oracle.backup.schema=SYSTEM
oracle.backup.directory=DATA_PUMP_DIR
oracle.backup.directory-path=/opt/oracle/admin/FREE/dpdump/5621983B6DFB0909E0630B00580A528D
oracle.backup.expdp-path=/Users/testing/oracle/instantclient_23_26/expdp
oracle.backup.docker-command=docker
oracle.backup.container=oracle-db-v2
oracle.backup.local-folder=./backups
oracle.backup.max-backups=5

# Test every minute
oracle.backup.cron=0 * * * * *